#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR/.." || echo "Could not find parent dir. Continuing anyway"

"$SCRIPT_DIR/test" -coverprofile cover.out "$@"
go tool cover -html=cover.out
