#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR/.." || echo "Could not cd to parent dir: you need to fix this"

rm -fr ./dist
mkdir ./dist

function one_dist() {
    rm -f ./evoimage ./evoimage.exe
    export GOOS=$1
    export GOARCH=$2
    echo "Building dist for $GOOS-$GOARCH"
    mkdir -p "./dist/$GOOS-$GOARCH"
    go build -v .
    mv evoimage* "./dist/$GOOS-$GOARCH/"
}

one_dist darwin 386
one_dist darwin amd64
one_dist linux 386
one_dist linux amd64
one_dist windows 386
one_dist windows amd64
